pomdp_model: /home/kuri/catkin_ws/src/markov_decision_making/mdm_kuri_example/src/MAHRC_1x3_v2_1.dpomdp
policy_file: /home/kuri/.madp/results/POMDP/MAHRC_1x3_v2_1/POMDP_MAHRC_1x3_v2_1_g0.9_PerseusPOMDPValueFunction_h999999
decision_horizon: 50
initial_action: stop_stop
initial_state: c_c_a_b
initial_state_belief: 1.0
observations: 
    - noVic_dan_noVic_noDan
    - noVic_noDan_noVic_noDan
    - noVic_noDan_vic_noDan
    - noVic_noDan_noVic_noDan