pomdp_model: /home/kuri/catkin_ws/src/markov_decision_making/mdm_kuri_example/src/MAHRC_6x5_randomDandV_v1.dpomdp
policy_file: /home/kuri/.madp/results/POMDP/MAHRC_6x5_randomDandV_v1/POMDP_MAHRC_6x5_randomDandV_v1
decision_horizon: 50
initial_action: stop_stop
initial_state: a_l_d_e
initial_state_belief: 1.0
observations: 
    - noVic_noDan_vic_noDan
    - noVic_dan_noVic_noDan
    - noVic_noDan_noVic_noDan
